version: '3'

services:

  mysql-server:
    image: mysql:8.3
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - nginx-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0.5
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      ZBX_STARTPOLLERS: "${ZBX_STARTPOLLERS}"
      ZBX_STARTPINGERS: "${ZBX_STARTPINGERS}"
      ZBX_STARTUNREACHABLE: "${ZBX_STARTUNREACHABLE}"
      ZBX_STARTSNMPPOLLERS: "${ZBX_STARTSNMPPOLLERS}"
      ZBX_STARTTRAPPERS: "${ZBX_STARTTRAPPERS}"
      ZBX_STARTDBSYNCERS: "${ZBX_STARTDBSYNCERS}"
      ZBX_TIMEOUT: "${ZBX_TIMEOUT}"
      ZBX_VALUECACHESIZE: "${ZBX_VALUECACHESIZE}"
      ZBX_HISTORYCACHESIZE: "${ZBX_HISTORYCACHESIZE}"
      ZBX_HISTORYINDEXCACHESIZE: "${ZBX_HISTORYINDEXCACHESIZE}"
      ZBX_CACHESIZE: "${ZBX_CACHESIZE}"
      ZBX_TRENDCACHESIZE: "${ZBX_TRENDCACHESIZE}"
      TZ: "${TZ}"
    depends_on:
      - mysql-server
    restart: unless-stopped
    networks:
      - nginx-net

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.0.5
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PHP_TZ: "${PHP_TZ}"
      TZ: "${TZ}"
    depends_on:
      - zabbix-server
      - mysql-server
    restart: unless-stopped
    networks:
      - nginx-net
    ports:
      - "8080:8080"

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.0.5
    container_name: zabbix-agent2
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    restart: always
    networks:
      - nginx-net

  grafana:
    image: grafana/grafana:12.0.2-security-01-ubuntu
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - nginx-net

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      - ./npm_data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    restart: unless-stopped
    networks:
      - nginx-net
    depends_on:
      - zabbix-server
      - grafana

volumes:
  mysql-data:
  grafana-data:
  npm_data:
  letsencrypt:

networks:
  nginx-net:
    driver: bridge
